import type { ProfileConfigSource } from './schema'

const profileConfig: ProfileConfigSource = {
  content: {
    username: '@reqb',
    siteTitle: 'torn apart',
    enterButtonLabel: 'click here',
    enterButtonAriaLabel: 'Enter profile',
    audioPlayLabel: 'Play audio',
    audioPauseLabel: 'Pause audio',
    playerTrackLabel: 'song.mp3',
    bannerLabel: new URL(document.URL).host,
    bannerAlt: 'torn banner',
    avatarAlt: 'Portrait of torn',
    handle: '@reqb',
    displayName: 'torn',
    pronouns: 'he / him',
    badgesAriaLabel: 'Discord badges',
    locationAriaLabel: 'Location',
    location: 'nowhere',
    bio: 'I love you',
    socialNavAriaLabel: 'Social links',
    nowPlayingLabel: '#1 nowplaying',
    lastfmLoadingTimestampLabel: 'loading',
    lastfmServiceStatusLabel: 'service status',
    lastfmUnavailableTitle: 'Now playing unavailable',
    lastfmLoadingTitle: 'loading last.fm scrobble',
    lastfmOfflineLabel: 'API OFFLINE',
    lastfmFallbackArtist: 'Last.fm / reqb',
    viewsOfflineLabel: 'offline',
    viewsLoadingLabel: '...',
    numberLocale: 'en-US',
  },
  assets: {
    backgroundVideoPath: 'assets/background.mp4',
    bannerPath: 'assets/banner.jpg',
    avatarPath: 'assets/pfp.jpg',
    songPath: 'assets/song.mp3',
  },
  socials: [
    { label: 'Discord', icon: 'discord', url: 'https://discord.gg/reqb' },
    { label: 'GitHub', icon: 'github', url: 'https://github.com/reqb' },
  ],
  badges: [
    { label: 'Bug Hunter Gold', icon: 'assets/discord_badges/bug_hunter_level_2.svg' },
    { label: 'Early Verified Bot Developer', icon: 'assets/discord_badges/early_verified_developer.svg' },
    { label: 'Server Booster 24 Months', icon: 'assets/discord_badges/boosting_24_months.svg' },
  ],
  features: {
    customCursorEnabled: true,
    cursorHaloEnabled: true,
    cardTiltEnabled: true,
    entryScreenEnabled: true,
    playerEnabled: true,
    viewCounterEnabled: true,
    animatedTitleEnabled: true,
    locationEnabled: true,
    pronounsEnabled: true,
    displayNameEnabled: true,
    bioEnabled: true,
  },
  api: {
    lastfmPath: '/api/lastfm',
    lastfmUsername: 'reqb',
    lastfmEnabled: false,
    viewsPath: '/api/views',
    refreshIntervalMs: 240_000,
  },
  theme: {
    accent: '#ff0000',
    accentSoft: '#810000',
    accentStrong: '#7a0000',
    warning: '#ffd86b',
    warningSoft: '#ffe29a',
  },
}

export default profileConfig
